biztweak_lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls')),
    path('accounts/', include('user_accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'lms'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('course/<int:id>', views.view_course, name='viewcourse'),
    path('course/enroll/<int:id>', views.enroll_course, name='enrollcourse'),
    path('course/enroll/module_start/<int:id>', views.start_module, name='startmodule'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'user_accounts'

urlpatterns = [
    path('register/', views.registerview, name='register'),
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
]

lms/models.py
from django.db import models

# Create your models here.

class Consultant(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=300)

    def __str__(self):
        return f'Consultant_{self.id}_{self.name}'

class Entrepreneur(models.Model):
    id = models.AutoField(primary_key=True)
    consultant_id = models.ForeignKey(Consultant, on_delete=models.CASCADE, related_name='entrepreneur')
    name = models.CharField(max_length=250)
    email = models.CharField(max_length=300)
    def __str__(self):
        return f'Entrepreneur_{self.id}_{self.name}'

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    consultant_id = models.ForeignKey(Consultant, on_delete=models.PROTECT, related_name='consultant_course')
    course_title = models.CharField(max_length=250)
    course_icon = models.CharField(max_length=250, blank=True)
    course_description = models.TextField(blank=True)

    def __str__(self):
        return f'Course_{self.id}_{self.course_title}'

class Course_module(models.Model):
    id = models.AutoField(primary_key=True)
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_module')
    module_title = models.CharField(max_length=250)
    module_description = models.TextField(blank=True)

    def __str__(self):
        return f'Module_{self.id}_{self.module_title}'

# store course_content with dynamic file name
def store_course_content_image(instance, filename):
    return f'module_content_image_id{instance.id}_{filename}'

def store_course_content_video(instance, filename):
    return f'module_content_video_id{instance.id}_{filename}'

def store_course_content_audio(instance, filename):
    return f'module_content_audio_id{instance.id}_{filename}'

class Course_content(models.Model):
    id = models.AutoField(primary_key=True)
    module_id = models.ForeignKey(Course_module, on_delete=models.CASCADE, related_name='course_content')
    content_title = models.CharField(max_length=500,blank=True)
    content_text = models.TextField(blank=True)
    content_image = models.ImageField(upload_to=store_course_content_image, default=None)
    content_video = models.FileField(upload_to=store_course_content_video, default=None)
    content_audio = models.FileField(upload_to=store_course_content_audio, default=None)

    def __str__(self):
        return f'Content_{self.id}_{self.content_title}'

class Course_quiz(models.Model):
    id = models.AutoField(primary_key=True)
    module_id = models.ForeignKey(Course_module, on_delete=models.CASCADE, related_name='course_quiz')
    quiz_title = models.CharField(max_length=250)
    quiz_description = models.TextField(blank=True)

    def __str__(self):
        return f'Quiz_{self.id}_{self.quiz_title}'

class Quiz_question(models.Model):
    id = models.AutoField(primary_key=True)
    quiz_id = models.ForeignKey(Course_quiz, on_delete=models.CASCADE,related_name='quiz_question')
    question_title = models.TextField()
    question = models.TextField()
    question_binary = models.BinaryField(max_length=None, blank=True)
    difficulty = models.IntegerField()

    def __str__(self):
        return f'Question_{self.id}_{self.question_title}'


class Answer(models.Model):
    id = models.AutoField(primary_key=True)
    entr_id = models.ForeignKey(Entrepreneur, on_delete=models.CASCADE, related_name='entr_answer')
    quiz_question = models.ForeignKey(Quiz_question, on_delete=models.CASCADE, related_name='quiz_name')
    answer = models.BinaryField(max_length=None, blank=True)
    answer_par = models.TextField()

    def __str__(self):
        return f'Answer_{self.id}_{self.entr_id}'

user_accounts/models.py
from django.db import models

# Create your models here.

lms/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import models


# Create your views here.
@login_required
def home(request):
    logged_user = request.user
    user_last_login = logged_user.last_login
    courses = models.Course.objects.all()
    return render(request, 'lms_main/home.html', {'logged_user':logged_user, 'courses': courses, 'user_last_login':user_last_login})

@login_required
def view_course(request, id):
    logged_user = request.user
    user_last_login = logged_user.last_login
    course = models.Course.objects.get(id=id)
    course_modules = models.Course_module.objects.filter(course_id=course.id)
    return render(request, 'lms_main/view_course.html', {'logged_user':logged_user, 'course':course, 'user_last_login':user_last_login, 'course_modules': course_modules})

@login_required
def enroll_course(request, id):
    course = models.Course.objects.get(id=id)
    course_modules = models.Course_module.objects.filter(course_id=course.id)
    # course_content = models.Course_content.objects.filter(module_id=)
    return render(request, 'lms_main/enroll_course.html', {'course':course, 'course_modules':course_modules})

@login_required
def start_module(request, id):
    course_content = models.Course_content.objects.filter(module_id=id)
    current_module = models.Course_module.objects.get(id=id) 
    course_modules = models.Course_module.objects.filter(course_id=current_module.course_id)
    course = models.Course.objects.get(id=current_module.course_id)


    return render(request, 'lms_main/start_module.html', {'course_content':course_content, 'current_module': current_module, 'course_modules': course_modules})

user_accounts/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def registerview(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            try:
                user = User.objects.get(email=email)
                return render(request, 'user_accounts/register.html', {'error': 'Email address has already been registered!'})
            except User.DoesNotExist:
                user = User.objects.create_user(firstname, email, password1)
                user.first_name= firstname
                user.last_name= lastname
                user.save()
                login(request, user)
                return redirect('lms:homepage')
    else:
        return render(request, 'user_accounts/register.html')

def loginview(request):
    if request.method == 'GET':
        return render(request, 'user_accounts/login.html')
    elif request.method == 'POST':
        name = request.POST['name']
        password = request.POST['password']
        user = authenticate(request, username=name, password=password)
        if user is not None:
            login(request, user)
            return redirect('lms:homepage')
        else:
            return render(request, 'user_accounts/login.html', {'error':'The Email and Password didn\'t match'})

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('lms:homepage')

lms/templates/lms_main/enroll_course.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="row">
        <div class="col-md-8">
            <div class="content">
                <h2>Welcome back to the course!</h2>
                <br>
                <br>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                </div>
                <p>Complete!</p>
                <br>
                <br>
                <div class="row">
                    <div class="col-md-4">
                        <div>
                            <div class="card" style="width: 18rem;">
                                <div class="card-header">
                                    Module 1 Scores
                                </div>
                                <div class="card-body">
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar" style="width: 78%" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100">78%</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <div class="card" style="width: 18rem;">
                                <div class="card-header">
                                    Module 2 Scores
                                </div>
                                <div class="card-body">
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                                    </div>
                                    <p>Not yet Complete</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-info mb-3" style="text-align: center;">
                <div class="card-header">
                    {{ course.course_title }}
                </div>
                <div class="card-body">
                    {{ course.course_icon | safe }}
                    <br>
                    <br>
                    {% for module in course_modules %}
                        <a href="/course/enroll/module_start/{{ module.id }}">
                            <div class="alert alert-primary" role="alert">
                                {{ module }}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

lms/templates/lms_main/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="container row">
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3">
                <!-- <div class="card-header"></div> -->
                <div class="card-body" style="text-align: center;">
                    <i style="font-size: 100px;" class="fas fa-address-card"></i>
                    <p><h5>Name: </h5>{{ logged_user.first_name }} {{ logged_user.last_name }}</p>
                    <p><h5>E-mail: </h5>{{ logged_user.email }}</p>
                    <small><h5>Last login: </h5>{{ logged_user.last_login }}</small>
                </div>


            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
            {% for course in courses %}
                    <div class="col-md-4" style="text-align: center;">
                        <div class="card text-white bg-info mb-3">
                            <div class="card-header">{{course.course_title}}</div>
                            <div class="card-body">
                                {{ course.course_icon | safe }}
                                <p>{{ course.course_description|slice:":100"  }}...</p>
                                <a class="btn btn-primary" href="/course/{{ course.id }}">View Course</a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
            </div>  
        </div>
    </div>

{% endblock %}

lms/templates/lms_main/start_module.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="row">
        <div class="col-md-8">
            <div class="content">

                {% for content in course_content %}
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="{{ course_content.content_video }}" allowfullscreen></iframe>
                    </div>
                    <br>
                    <p>{{ course_content.content_text }}</p>
                {% endfor %}
                
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-info mb-3">
                <div class="card-header">
                    {{ course.course_title }}
                </div>
                <div class="card-body">
                    {{ course.course_icon | safe }}
                    <br>
                    {% for module in course_modules %}
                        <a href="/course/enroll/module_start/{{ module.id }}">
                            <div class="alert alert-primary" role="alert">
                                {{ module }}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

lms/templates/lms_main/view_course.html
{% extends 'base.html' %}

{% block content %}

    <div class="container row">
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3">
                <!-- <div class="card-header"></div> -->
                <div class="card-body" style="text-align: center;">
                    <i style="font-size: 100px;" class="fas fa-address-card"></i>
                    <p><h5>Name: </h5>{{ logged_user.first_name }} {{ logged_user.last_name }}</p>
                    <p><h5>E-mail: </h5>{{ logged_user.email }}</p>
                    <small><h5>Last login: </h5>{{ logged_user.last_login }}</small>
                </div>


            </div>
        </div>
        <div class="col-md-8">
            <div class="card text-white bg-info mb-3">
                <div class="card-header">
                    {{ course.course_title }}
                </div>
                <div class="card-body">
                    {{ course.course_icon | safe }}
                    <p>{{ course.course_description }}</p>
                    <hr>
                    <h4>Course Modules</h4>
                    <ol>
                        {% for module in course_modules %}
                            <li>
                                <p>{{ module.module_title }} - <span>{{ module.module_description }}</span></p>
                            </li>
                        {% endfor %}
                    </ol>
                    
                    <a class="btn btn-primary" href="/course/enroll/{{ course.id }}">Enroll</a>
                </div>
            </div>  
        </div>
    </div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/eea5eab299.js" crossorigin="anonymous"></script>

    <title>BizTweak LMS</title>
    <!-- <style>
      * {
        border: 1px solid red;
      }
    </style> -->
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'lms:homepage' %}">BizTweak LMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="nav-item"><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li>
          <li class="nav-item">
            <form id="logout" method="POST" action="{% url 'user_accounts:logout' %}">
              {% csrf_token %}
              <input type="hidden">
            </form>
          </li>
          {% else %}
          <li class="nav-item"><a href="{% url 'user_accounts:register' %}">Signup</a></li>
          <li class="nav-item"><a href="{% url 'user_accounts:login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <br><br>
        {% block content %}
        {% endblock %}
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>BizTweak LMS</title>
  </head>
  <body>
    
    <div class="container" style="padding: 100px;">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

user_accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
<br />
{% endif %}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">Login</div>
            <div class="card-body">
                <form method="POST" action="{% url 'user_accounts:login' %}">
                    {% csrf_token %}
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">First name</span>
                      </div>
                      <input name="name" type="name" class="form-control" placeholder="Jon" aria-label="name" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Password</span>
                      </div>
                      <input name="password" type="password" class="form-control" aria-label="password" aria-describedby="basic-addon1">
                    </div>

                    <br>
                    <input class="btn btn-primary" type="submit" value="Login">
                </form>
            </div>
          </div>
    </div>
</div>


{% endblock %}

user_accounts/templates/user_accounts/login.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
<br />
{% endif %}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">Login</div>
            <div class="card-body">
                <form method="POST" action="{% url 'user_accounts:login' %}">
                    {% csrf_token %}
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">First name</span>
                      </div>
                      <input name="name" type="name" class="form-control" placeholder="Jon" aria-label="name" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Password</span>
                      </div>
                      <input name="password" type="password" class="form-control" aria-label="password" aria-describedby="basic-addon1">
                    </div>

                    <br>
                    <input class="btn btn-primary" type="submit" value="Login">
                </form>
            </div>
          </div>
    </div>
</div>

{% endblock %}

user_accounts/templates/user_accounts/register.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
<br />
{% endif %}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">Register</div>
            <div class="card-body">
                <form method="POST" action="{% url 'user_accounts:register' %}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">First Name</span>
                      </div>
                      <input name="firstname" type="name" class="form-control" placeholder="Jon" aria-label="firstname" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Last Name</span>
                      </div>
                      <input name="lastname" type="name" class="form-control" placeholder="Deo" aria-label="lastname" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Email</span>
                      </div>
                      <input name="email" type="email" class="form-control" placeholder="user@example.com" aria-label="email" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Password</span>
                      </div>
                      <input name="password1" type="password" class="form-control" aria-label="password1" aria-describedby="basic-addon1">
                    </div>
                  
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Confirm Password</span>
                      </div>
                      <input name="password2" type="password" class="form-control" aria-label="password2" aria-describedby="basic-addon1">
                    </div>
                    <br>
                    <input class="btn btn-primary" type="submit" value="Register">
                </form>
            </div>
          </div>
    </div>
</div>

{% endblock %}